version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./data:/app/data  # SQLite database storage
    environment:
      - ENV=${ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/game.db}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - SECRET_KEY=${SECRET_KEY:-default_dev_key_please_change}
      - AUDIO_ENABLED=${AUDIO_ENABLED:-true}
      - PROGRESSION_ENABLED=${PROGRESSION_ENABLED:-true}
      - CHALLENGES_ENABLED=${CHALLENGES_ENABLED:-true}
  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  data:  # Named volume for database persistence
