version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
