#!/usr/bin/env python3
import subprocess
import sys
import glob
import os

files = glob.glob('tests/**/test_*.py', recursive=True)
exit_code = 0
for f in files:
    env = os.environ.copy()
    env['PYTHONPATH'] = '.'
    result = subprocess.run([sys.executable, f], env=env)
    if result.returncode != 0:
        exit_code = result.returncode
sys.exit(exit_code)
