name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r server/requirements.txt
          pip install pytest
          npm install
      - name: Lint JS
        run: npm run lint
      - name: Test Python
        run: pytest
      - name: Test JS
        run: npm test
